[model]
latent_dim = 128
T = 20
batch_size = 8
num_epoch = 1
outdir = SPEEDY/decoder_transformer_dim128_sparsest_Gaussian
lr = 1e-4
arch = decoder_transformer_sparsest
max_norm = 1.0
dropout = 0.0
warmup_steps = 2000
lr_scaling_steps = 182500
model_seed = 10000
q_distribution = Gaussian

[data]
obs_setting = sparsest

[others]
gpu_index = 7